apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-gateway-1-19-3
  namespace: istio-gateways
spec:
  profile: empty
  tag: 1.19.3
  revision: 1-19-3
  components:
    ingressGateways:
      - name: istio-ingressgateway-1-19-3
        namespace: istio-gateways
        enabled: true
        label:
          istio: ingressgateway
          version: 1-19-3
          app: istio-ingressgateway
        k8s:
          hpaSpec:
            maxReplicas: 2
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 60
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway-1-19-3
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          service:
            # Since we created our own LoadBalanced service, tell istio to create a ClusterIP service for this gateway
            type: ClusterIP
            # match the LoadBalanced Service
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: tcp
                port: 31400
                targetPort: 31400
              - name: tls
                port: 15443
                targetPort: 15443
